kind: pipeline
type: docker
name: amd64

platform:
  arch: amd64

steps:
  - name: Build & Test
    image: ubuntu:20.04
    commands:
      - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
      - apt update && apt install -y curl git unzip xz-utils zip libglu1-mesa openjdk-8-jdk wget
      # - useradd -ms /bin/bash developer
      # - USER developer
      # - WORKDIR /home/developer
      - mkdir -p /home/Android/sdk
      - ls /home
      - cd /home
      - ANDROID_SDK_ROOT=/home/Android/sdk
      - mkdir -p .android && touch .android/repositories.cfg
      - wget -O sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
      - unzip sdk-tools.zip && rm sdk-tools.zip
      - mv tools Android/sdk/tools
      - ls /home/Android
      - ls /home/Android/sdk
      - ls /home/Android/sdk/tools
      - cd Android/sdk/tools/bin && yes | ./sdkmanager --licenses
      - cd Android/sdk/tools/bin && ./sdkmanager "build-tools;29.0.2" "patcher;v4" "platform-tools" "platforms;android-29" "sources;android-29"
      - PATH="$PATH:/home/Android/sdk/platform-tools"
      - cd /home
      - git clone https://github.com/flutter/flutter.git
      - PATH="$PATH:/home/flutter/bin"
      - flutter test
      - dart test_cov_console 

  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
